### ISSUE TITLE
[TASK] 이승준 / 로그인 유지 및 유저 데이터 받아오기 구현/ 2022-06-10

### ISSUE THREAD

**Issue by seungjun0423** [codestates/OhWunWan#139]
### ISSUE
- Group:  `client`, 
- Type:  `feature`,
- Detail: `쿠키를 이용해 지속적으로 서버와 통신하며 인증과정을 거치고 인증된 유저에 해당한다면 그 유저에 해당하는 데이터를 가져오는 기능 구현`

### TODO
1. [x] 로그인 상태를 리덕스를 이용해 관리
2. [x] useEffect를 이용한 로그인 상태 유지
3. [x] axios를 이용한 서버와의  통신과 데이터 가져오기 

### Labels
- Estimated time: `E: 1h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`, `Middle`, `Low`
