### ISSUE TITLE
[TASK] 황지웅 / becn_1rm & becn_1rm_comment & becn_1rm_respect api 작성 / 2022-06-14

### ISSUE THREAD

**Issue by woong8249** [codestates/OhWunWan#169]
### ISSUE
- Group:  `server`
- Type:`feature`
- Detail: `api 작성`

### TODO
0. [x] sequelize.fn('COUNT')&
 group by &
  having  & 
   sequelize.literal('(RANK~) 이해하기
1. [x] becn_1rm api 작성(get, post, patch, delete)
2. [x] becn_1rm_comment api 작성(post, patch, delete)
3. [x] becn_1rm_respect api 작성(post,  delete)

### Estimated time
> Pick one
