### ISSUE TITLE
[TASK] 이름 / 작업내용 / 2022-00-00

### ISSUE THREAD

**Issue by youngs508** [codestates/OhWunWan#88]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: HTTPS 배포에 대한 이론과 실전을 대비한 완벽한 이해

### TODO
1. [ ] EC2를 준비해 놓는다.
2. [ ] S2에 대해서도 어떻게 과제를 수행할 지에 대해서 준비해 놓는다.
3. [ ] CloudFront, Route53, AWS Certificate에 대해서도 준비한 대로 배포를 진행한다. 

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 1h`
- Group : `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `Middle`
